PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
PREFIX image:   <http://jibbering.com/vocabs/image/#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>

CONSTRUCT { ?img foaf:depicts ?who . }

WHERE {
    ?img  image:hasPart ?part .
    ?part foaf:depicts ?who .
}

